language: cpp  # Travis-CI does not currently support Python and Mac OS X

matrix:
  include:
    - os: linux
      dist: xenial
      env: PYTHON_VERSION=3.6
    - os: linux
      dist: trusty
      env: PYTHON_VERSION=3.6
    - os: linux
      dist: xenial
      env: PYTHON_VERSION=3.7
    - os: osx
      env: PYTHON_VERSION=3.6

  fast_finish: true
  allow_failures:
    - os: linux
      dist: trusty
      env: PYTHON_VERSION=3.6
    - os: linux
      dist: xenial
      env: PYTHON_VERSION=3.7
    - os: osx
      env: PYTHON_VERSION=3.6

install:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&
      curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
    else
      sudo apt-get update;
      sudo apt-get install -y xvfb;
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$PYTHON_VERSION
  - source activate test-environment
  - pip install PySide2
  - conda install numpy matplotlib-base gdal pyproj
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      conda remove --force PyQt Qt sip;
      export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib:$LD_LIBRARY_PATH;
    fi
  - pip install cython
  - pip install coveralls
  - pip install https://github.com/hydroffice/hyo2_abc/archive/master.zip
  - pip install .
  - rm -f $HOME/miniconda/envs/test-environment/qt.conf
  - pip install pytest pytest-cov
  - conda list --show-channel-urls

script:
  - py.test --cov

after_script:
  - coverage report -m

after_success:
  - pip install PyYAML
  - coveralls
